Maintenance
test-fullautomation/robotframework-tutorial pull request #18
Opened 2022-12-13 15:21 UTC by HolQue

2022-12-13 16:08 UTC, test-fullautomation requested changes
Hi Holger,

looks good to me!
Please check my findings.

Thank you,
 Thomas

2022-12-13 16:08 UTC, test-fullautomation commented on 100_variables_and_datatypes/doc_src/tutorial-01.robot.rst
> +Where necessary the Robot Framework automatically converts the data types to enable arithmetic computations and catenations.
Hi Holger,
now I'm confused.

Our tutorial is specific for  RobotFramework AIO. Therefore it makes sense to refer to it.
In this case here of course there is no contribution of RobotFramework AIO, this is Robot Framework Core functionality, thereore Robot Framework is correct.

But if meaningful RobotFramework AIO can be referenced in this tutorial, too.

Thank you,
 Thomas

2022-12-13 16:08 UTC, test-fullautomation commented on README.rst
> +This Robot Framework tutorial contains robot code examples together with the documentation explaining how to use these
Here we would have ``RobotFramework AIO`` tutorial. This is what is is.

2022-12-13 17:16 UTC, HolQue commented on README.rst
> +This Robot Framework tutorial contains robot code examples together with the documentation explaining how to use these
Hi Thomas,

as per PyPi stand-alone philosophy of the described components I removed all references to "AIO".

2022-12-14 10:20 UTC, test-fullautomation commented on README.rst
> +This Robot Framework tutorial contains robot code examples together with the documentation explaining how to use these
Hi Holger,
very good!
Thank you,
Thomas

2023-01-09 14:56 UTC, test-fullautomation approved these changes
Hi Holger,
looks good to me!
Thank you,
 Thomas

2023-01-09 14:57 UTC, merged